name: zoom-client
base: core18
adopt-info: zoom
summary: ZOOM Cloud Meetings
description: |
  Video conferencing with real-time messaging and content sharing

  https://zoom.us provides simplified video conferencing, whiteboard sharing
  and messaging across any device. This is an unofficial re-pack of the debian
  package provided by zoom.us

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  zoom-client:
    command: bin/launcher.sh
    command-chain:
       - bin/desktop-launch
       - snap/command-chain/alsa-launch
       - bin/private-fontcache
    environment:
      LD_LIBRARY_PATH: $SNAP/zoom/Qt/lib:$SNAP/zoom:$LD_LIBRARY_PATH
      DISABLE_WAYLAND: 1
      ALWAYS_USE_PULSEAUDIO: 1
    desktop: usr/share/applications/Zoom.desktop
    plugs:
      - audio-playback
      - audio-record
      - camera
      - desktop
      - hardware-observe
      - home
      - network
      - network-bind
      - network-manager-observe
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-observe
      - unity7
      - wayland
      - x11

hooks:
  configure:
    plugs: [ desktop ]

layout:
  /sbin/killall5:
    bind-file: $SNAP/sbin/killall5
  /usr/bin/lscpu:
    bind-file: $SNAP/usr/bin/lscpu
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
  alsa-mixin:
    plugin: dump
    after: [ qt5 ]
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  zoom:
    source: https://zoom.us/client/latest/zoom_amd64.deb
    source-type: deb
    plugin: nil
    after: [ alsa-mixin ]
    override-build: |
      # unset hardcoded LD_LIBRARY_PATHs
      sed -i s/D_LIBRAR/XXXXXXXX/g opt/zoom/ZoomLauncher
      sed -i s/T_AUTO_S/XXXXXXXX/g opt/zoom/ZoomLauncher
      sed -i s/LD_LIBRARY_PATH/XXXXXXXXXX_PATH/g opt/zoom/libQt5Network.so.5.*.* opt/zoom/zopen

      sed -i "s;Prefix=/opt;Prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current;" opt/zoom/qt.conf
      cp -av opt/zoom $SNAPCRAFT_PART_INSTALL/
      cp -av usr $SNAPCRAFT_PART_INSTALL/

      # remove danging symlink
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/zoom

      # fix icon and exec lines in desktop file
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/pixmaps/Zoom.png|g' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/Zoom.desktop
      sed -i 's|Exec=.*|Exec=zoom-client %U|g' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/Zoom.desktop

      VER="$(strings $SNAPCRAFT_PART_INSTALL/zoom/zoom|grep \
           "($(cat $SNAPCRAFT_PART_INSTALL/zoom/version.txt|sed 's/^[0-9].[0-9].//'))" | \
           sed 's/(//;s/)//;s/ /-/')"
      snapcraftctl set-version "$VER"
    build-packages:
      - binutils
    stage-packages:
      - ibus
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libdbus-1-3
      - libegl1-mesa
      - libepoxy0
      - libfontconfig1
      - libgtk-3-0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglib2.0-0
      - libgnutls30
      - libgnutls-openssl27
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libpulse-mainloop-glib0
      - libqt53dcore5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53dquick5
      - libqt53dquickscene2d5
      - libqt53drender5
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5network5
      - libqt5printsupport5
      - libqt5qml5
      - libqt5quickcontrols2-5
      - libqt5quickparticles5
      - libqt5quicktemplates2-5
      - libqt5quick5
      - libqt5sql5
      - libqt5waylandclient5
      - libqt5widgets5
      - libqt5gui5
      - libqt5xmlpatterns5
      - libsm6
      - libsqlite3-0
      - libssl1.0.0
      - libtinfo5
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libx11-6
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-xtest0
      - libxcomposite1
      - libxcursor1
      - libxi6
      - libxinerama1
      - xkb-data
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxtst6
      - pulseaudio-utils
      - sysvinit-utils
      - util-linux
      - x11-xserver-utils
  yaru-cursors:
    plugin: nil
    after: [ zoom ]
    override-build: |
      URL1="https://launchpad.net/ubuntu/focal/amd64/yaru-theme-icon"
      URL2="https://launchpad.net/ubuntu/focal/+package/yaru-theme-icon"
      DEB="$(wget -q -O- $URL1/$(wget -q -O- $URL2|grep amd64|grep href| \
           sed 's/^.*\///;s/\".*$//'|tail -1)|grep \\.deb|sed 's/^.*href=\"//;s/\".*$//')"
      wget -q -O- $DEB | dpkg -x - .
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/Yaru
      cp -a usr/share/icons/Yaru/cursors $SNAPCRAFT_PART_INSTALL/usr/share/icons/Yaru/
      cp -a usr/share/icons/Yaru/cursor.theme $SNAPCRAFT_PART_INSTALL/usr/share/icons/Yaru/
    build-packages:
      - wget
  snap-helpers:
    plugin: dump
    after: [ yaru-cursors ]
    source: snap/local/scripts
    organize:
      private-fontcache: bin/private-fontcache
  cleanup:
    source: .
    plugin: nil
    after: [ snap-helpers ]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av launcher.sh $SNAPCRAFT_PART_INSTALL/bin/
    override-prime: |
      snapcraftctl prime
      # remove any duplicated libs
      for lib in $(find $SNAPCRAFT_PRIME/zoom/ -name '*lib*'); do
        echo "checking duplicates: $(basename $lib)"
        if ! echo "$lib" | grep -q -e "libicuuc.so" -e "libicui18n.so" -e "libicudata.so"; then
          for files in $(find $SNAPCRAFT_PRIME/usr $SNAPCRAFT_PRIME/lib -name "*$(basename $lib)*"); do
            rm -fv $files
          done
        fi
      done
      # Qt needs libssl 1.0 and gets confused if 1.1 is around
      rm usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libssl.so.1.1
      rm usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcrypto.so.1.1
      # clean up unused cruft
      for CRUFT in bug lintian man themes; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      # drop unused icon themes (keep cursors)
      for icons in $(ls -d usr/share/icons/*); do
        ICONS="$(basename "$icons")"
        if [ "$ICONS" != "Yaru" ] && [ "$ICONS" != "DMZ-White" ] && [ "$ICONS" != "DMZ-Black" ]; then
          rm -rf usr/share/icons/$ICONS
        fi
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
      rm -rf $SNAPCRAFT_PRIME/usr/lib/gcc
