name: zoom-client
base: core22
adopt-info: zoom
summary: ZOOM Cloud Meetings
description: |
  Video conferencing with real-time messaging and content sharing

  https://zoom.us provides simplified video conferencing, whiteboard sharing
  and messaging across any device. This is an unofficial re-pack of the debian
  package provided by zoom.us

grade: stable
confinement: strict
compression: lzo
assumes:
  - snapd2.55

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  zoom-client:
    command: bin/launcher.sh
    command-chain:
      - snap/command-chain/alsa-launch
    environment:
      LD_LIBRARY_PATH: $SNAP/zoom/Qt/lib:$SNAP/zoom:$SNAP/zoom/cef:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      ALWAYS_USE_PULSEAUDIO: 1
    desktop: usr/share/applications/Zoom.desktop
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - audio-record
      - browser-sandbox
      - camera
      - desktop
      - gsettings
      - hardware-observe
      - home
      - network
      - network-bind
      - network-manager-observe
      - opengl
      - pulseaudio
      - removable-media
      - screencast-legacy
      - screen-inhibit-control
      - shared-memory
      - system-observe
      - unity7
      - wayland
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  shared-memory:
    private: true

hooks:
  configure:
    plugs:
      - system-observe

slots:
  dummymq:
    interface: posix-mq
    path: [/zoom,]
    permissions:
      - read
      - write
      - create
      - delete

layout:
  /etc/os_release:
    symlink: $SNAP_DATA/os-release

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  zoom:
    source: https://zoom.us/client/latest/zoom_amd64.deb
    source-type: deb
    plugin: nil
    override-build: |
      # unset hardcoded LD_LIBRARY_PATHs
      sed -i s/D_LIBRAR/XXXXXXXX/g opt/zoom/ZoomLauncher
      sed -i s/T_AUTO_S/XXXXXXXX/g opt/zoom/ZoomLauncher
      sed -i s/LD_LIBRARY_PATH/XXXXXXXXXX_PATH/g opt/zoom/Qt/lib/libQt5Network.so.* opt/zoom/zopen

      # try fixing hardcoded /etc/os-release to allow wayland screen sharing
      sed -i "s;/os-release;/os_release;" opt/zoom/zoom
      sed -i "s;/os-release;/os_release;" opt/zoom/Qt/lib/libQt5Core.so.*

      sed -i "s;Prefix=/opt;Prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current;" opt/zoom/qt.conf
      cp -av opt/zoom $SNAPCRAFT_PART_INSTALL/
      cp -av usr $SNAPCRAFT_PART_INSTALL/

      # remove danging symlink
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/zoom

      # fix icon and exec lines in desktop file
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/pixmaps/Zoom.png|g' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/Zoom.desktop
      sed -i 's|Exec=.*|Exec=zoom-client %U|g' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/Zoom.desktop

      VER="$(strings $SNAPCRAFT_PART_INSTALL/zoom/zoom | \
           grep "[0-9].[0-9]*.[0-9] ([0-9]*)" | \
                                             head -1 | \
                                             sed 's/ (/./;s/)//')"
      craftctl set version="$VER"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av $SNAPCRAFT_PROJECT_DIR/launcher.sh $SNAPCRAFT_PART_INSTALL/bin/
    build-packages:
      - binutils
    stage-packages:
      - libaom3
      - libcodec2-1.0
      - libdav1d5
      - libdouble-conversion3
      - libgsm1
      - libx264-163
      - libx265-199
      - libmd4c0
      - libmfx1
      - libnuma1
      - libqt53danimation5
      - libqt53dcore5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53dquick5
      - libqt53dquickscene2d5
      - libqt53drender5
      - libqt5concurrent5
      - libqt5gamepad5
      - libqt5gui5
      - libqt5gui5-gles
      - libqt5multimedia5
      - libqt5quickparticles5
      - libqt5quickparticles5-gles
      - libqt5remoteobjects5
      - libqt5sql5
      - libqt5xmlpatterns5
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-util1
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxcb-xtest0
      - libxkbcommon-x11-0
      - libxvidcore4
      - libzvbi0
      - pulseaudio-utils
    stage:
      - -usr/lib/x86_64-linux-gnu/libharfbuzz.*
    prime: # remove all of mesa, we want to use it from the extension
      - -usr/lib/x86_64-linux-gnu/dri
      - -usr/lib/x86_64-linux-gnu/libgbm.so.1
      - -usr/lib/x86_64-linux-gnu/libgbm.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libglapi.so.0
      - -usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
      - -usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libEGL.so.1
      - -usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
      - -usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libGLESv2.so.2
      - -usr/lib/x86_64-linux-gnu/libGL.so.1
      - -usr/lib/x86_64-linux-gnu/libGL.so.1.7.0
      - -usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libGLX.so.0
      - -usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
  cleanup:
    source: .
    plugin: nil
    after: [ zoom ]
    override-prime: |
      craftctl default
      # remove any duplicated libs
      for lib in $(find $SNAPCRAFT_PRIME/zoom/ -type f -name "*.so*"); do
        echo "checking duplicates: $(basename $lib)"
        for files in $(find $SNAPCRAFT_PRIME/usr $SNAPCRAFT_PRIME/lib -name "*$(basename $lib)*" -type f); do
          rm -fv $files
        done
      done
      # clean up unused cruft
      for CRUFT in bug lintian man themes; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      # drop all docs except licenses
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
